---
- name: Copy site.conf
  become: yes
  copy: src=site.conf dest=/etc/nginx/sites-available/site.conf
  notify: Reload nginx

- name: Disable default site
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: Reload nginx

- name: Enable site
  become: yes
  file: src=/etc/nginx/sites-available/site.conf dest=/etc/nginx/sites-enabled/site state=link
  notify: Reload nginx